/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { Context } from "../Context";

export class Context__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Context {
    return new Contract(address, _abi, signerOrProvider) as Context;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "c__0x332238ce",
        type: "bytes32",
      },
    ],
    name: "c_0x332238ce",
    outputs: [],
    stateMutability: "pure",
    type: "function",
  },
];
